### ISSUE TITLE
can not install

### ISSUE THREAD

**Issue by xralphack** [samkitano/aktiv8me#1]
php artisan make:aktiv8me

[ReflectionException]
Method Kitano\Aktiv8me\Console\MakeEmailVerification::handle() does not exist

**Comment by samkitano** [comment]
laravel version?

**Comment by xralphack** [comment]
5.5

**Comment by samkitano** [comment]
There have been some changes in the way Laravel handles artisan commands. Unfortunately, I haven't had the time to read the migration docs thoroughly and to test this package in 5.5 yet.

I'll merge a compatible version as soon as I have some time available.

Meanwhile, I would appreciate if you can open ```vendor/kitano/aktiv8me/src/Console/MakeEmailVerification.php``` and change line 115 from:

`public function fire()`

to:

`public function handle()`

Let me know if it sufficed. Please notice that this is NOT a solution, as it will be overwritten everytime you run composer.

**Comment by xralphack** [comment]
it works ~

**Comment by samkitano** [comment]
thanks :)

I will release a 5.5 compatible version as soon as possible.

**Comment by xralphack** [comment]
thank you 👍
