### ISSUE TITLE
resend routes not working!

### ISSUE THREAD

**Issue by sajidzaman** [samkitano/aktiv8me#3]
`Route::get('/aktiv8me/resend', '\App\Http\Controllers\Auth\RegisterController@resend');
Route::post('/aktiv8me/resend', '\App\Http\Controllers\Auth\RegisterController@resend')->name('register.resend');`

Above resend routes are showing error.

**Comment by samkitano** [comment]
I'm sorry but I'll need more information to reproduce your problem and figure out what's wrong:

What error? Please be explicit.

What version of laravel?

What version of the package?

Did you run **php artisan make:aktiv8me** ?

Did it finish without errors?

Did you try to reinstall?

I will assume both issues you opened are related.

**Comment by sajidzaman** [comment]
Laravel 5.5 fresh installation
Error was method resend not defined in RegisterController
yes i did run php artisan make:aktiv8me ...

But it did not make the view file for resend. 
I did finish by fixing route to

Route::get('/aktiv8me/resend', '\App\Http\Controllers\Auth\RegisterController@getResend');
Route::post('/aktiv8me/resend', '\App\Http\Controllers\Auth\RegisterController@postresend')->name('register.resend');

and then copying the view file from the repository to my local machine..

**Comment by samkitano** [comment]
Glad you managed :)
